name: Xcode - Build and Analyze
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Analyze (Xcode)
    runs-on: macos-latest
    strategy:
      matrix:
        scheme: ["default"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect Xcode scheme
        id: scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo "scheme=$default" >> $GITHUB_OUTPUT
          echo "Using scheme: $default"

      - name: Build and Analyze
        run: |
          scheme="${{ steps.scheme.outputs.scheme }}"
          if [ "$(ls -A | grep -i \.xcworkspace$)" ]; then filetype_parameter="workspace" && file_to_build="$(ls -A | grep -i \.xcworkspace$)"; else filetype_parameter="project" && file_to_build="$(ls -A | grep -i \.xcodeproj$)"; fi
          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | tee build.log | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload Build Log
        uses: actions/upload-artifact@v4
        with:
          name: xcode-build-log
          path: build.log
